# Generated by Django 6.0.3 on 2026-03-20 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('surname', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('photo_url', models.CharField(blank=True, default='', max_length=500)),
                ('following_borsch', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Borsch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('grams', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type_meat', models.TextField(blank=True, default='')),
                ('extras', models.TextField(blank=True, default='')),
                ('dish_features', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('rating_count', models.IntegerField(default=0)),
                ('rating_sum', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'borschi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'places',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, default='')),
                ('rating_salt', models.IntegerField(default=0)),
                ('rating_meat', models.IntegerField(default=0)),
                ('rating_beet', models.IntegerField(default=0)),
                ('rating_density', models.IntegerField(default=0)),
                ('rating_aftertaste', models.IntegerField(default=0)),
                ('rating_serving', models.IntegerField(default=0)),
                ('overall_rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('borschi', models.ForeignKey(db_column='borschi_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.borsch')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.appuser')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(db_column='comment_id', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment_replies', to='core.appuser')),
            ],
            options={
                'db_table': 'comment_replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='borsch',
            name='place',
            field=models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, related_name='borsches', to='core.place'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_salt', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rating_meat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rating_beet', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rating_density', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rating_aftertaste', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rating_serving', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('borschi', models.ForeignKey(db_column='borschi_id', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.borsch')),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(db_column='comment_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.comment')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='core.appuser')),
            ],
            options={
                'db_table': 'comment_likes',
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteBorsch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borsch', models.ForeignKey(db_column='borsch_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.borsch')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.appuser')),
            ],
            options={
                'db_table': 'favorite_borschi',
                'unique_together': {('user', 'borsch')},
            },
        ),
    ]
